### PR TITLE
Swap 3.2.3

### PR DESCRIPTION
**Pull request by DJVova**
- Deleted RandomX from code and Repo
- Deleted Unbound lib. Now It not compile every time. Using external unbound lib
- Fix compiles on Windows with MinGW 32/64
- Now SWAP takes up less space and compiles faster on all systems
- Fix problems with RPC-wallet
- Adding ZMQ/Pub support for txpool_add and chain_main events
- Some minor fixes

### CODE REVIEW

**Comment by one-and-only** [comment]
@DJVova what did you fix in the RPC-wallet?

**Comment by DJVova** [comment]
I do nothing with RPC by myself, but I add RPC fixes from others people's and now tx_notify function works good, I test it in windows rpc-wallet. This function not worked on Graviex server. Now, I hope, it will work good.  среда, 10 апреля 2024г., 19:51 +07:00 от Antonios Papadakis  ***@***.*** :

**Comment by one-and-only** [comment]
@DJVova It seems like the code you are including adds CLSAG transactions. This is code that requires a hardfork if implemented fully. I would require you to remove the code that adds CLSAG before I can merge this. I'll let you of any other issues. I'm still checking the code. Here is one of the commits for example: https://github.com/swap-dev/swap/pull/17/commits/0c5794c1f863d73899dd6610d8561f9ae6a3ef08

**Comment by one-and-only** [comment]
This version isn't supposed to add new features. Only fix builds for supported platforms and maybe fix bugs that have been fixed in monero upstream.

**Comment by one-and-only** [comment]
I'd actually recommend only changing stuff that allowed the build process to be fixed. Any other big changes should be multiple pull requests to test small parts each time. Thanks.

**Comment by DJVova** [comment]
I can revert commit with CLSAG, but this commit - only preparing to CLSAG. Not need hardfork, I checked this. Maybe not revert? Less work in the future...  среда, 10 апреля 2024г., 20:29 +07:00 от Antonios Papadakis  ***@***.*** :

**Comment by DJVova** [comment]
- Adding ZMQ/Pub support
This is new function from Monero upstream среда, 10 апреля 2024г., 20:29 +07:00 от Antonios Papadakis  ***@***.*** :

**Comment by DJVova** [comment]
OK, next time I will send a PR after each 1-5 commits среда, 10 апреля 2024г., 20:30 +07:00 от Antonios Papadakis  ***@***.*** :

**Comment by one-and-only** [comment]
Even if it prepares for CLSAG we shouldn't have it if were not going to update to CLSAG. It adds more complexity and code size. It would get compiled in for no reason.

Here's what I'll say...Commit the code that you know is needed to make the build work for you (you said you were having trouble building on windows.) If you want to add bug fixes or features, that's for a new PR. I'm debating whether I should close this PR.

**Comment by DJVova** [comment]
Ok, you can close this PR, i will revert 2 CLSAG commits. I agree that this function is not required now. We can add it later. I think, the rest of the commits are useful, including commits with new ZMQ function.

I did a lot of work adding these commits. After adding each commit, I had to recompile everything and check for functionality. Of course, I understand that now it’s difficult to double-check it all at once, but I wouldn’t want to delete it and then redo it all again. This takes a lot of time (

Another reason why I don't want to revert commits CLSAG too. In this case, Github will create 2 new commits that cancel the old ones. And later we will add them anyway. Empty work. Or maybe you know how delete selected commits without create new ?

**Comment by one-and-only** [comment]
Look into git rebase. You should be able to revert commits without creating a new one. I don't know if we'll ever end up adding CLSAG to be honest. I'll be on the lookout for new PRs and review them as they are creating. Thank you for your contribution.

**Review by one-and-only — COMMENTED** [review]
The changes in this PR don't fit the scope of its original goal of fixing build issues and minor bug fixes, if applicable.

**Pull request closed without merging**
