### PR TITLE
Swap 3.3.0a1

### PR DESCRIPTION
**Pull request by DJVova**
- Deleted RandomX from code and Repo
- Deleted Unbound lib. Now It not compile every time. Using external unbound lib
- Fix compiles on Windows with MinGW 32/64
- Now SWAP takes up less space and compiles faster on all systems
- Fix problems with RPC-wallet
- Adding ZMQ/Pub support
- Some minor fixes

### CODE REVIEW

**Comment by DJVova** [comment]
I deleted commits with CLSAG. Please check. I think there is no need to make release versions until we launch it on the Graviex server. This may require additional changes.

**Comment by one-and-only** [comment]
Thanks for this. I will check it soon.

**Comment by one-and-only** [comment]
@DJVova What command did you use to build swap? I'm using the standard build steps and I'm not able to build using cmake and make.

**Comment by one-and-only** [comment]
Here is what I get when I try to clone the repo with submodules:
clone error

**Comment by one-and-only** [comment]
if I clone the main repository with the submodules and then apply your changes with `git pull`, then I will get an include error because your submodules changed.

**Comment by DJVova** [comment]
To build swap, i'm using standart commands too - as in readme.

About miniupnp module...i'm checked now: I only change path from 
https://github.com/monero-project/miniupnp direct to
https://github.com/miniupnp/miniupnp as in monero now.
But In addition, the file external/miniupnp has changed:
Submodule [miniupnp](https://github.com/miniupnp/miniupnp) updated [from 4c700e to 27d340](https://github.com/miniupnp/miniupnp/compare/4c700e09526a7d546394e85628c57e9490feefa0...27d34098a331e4468a02adf65108bf74cae39ed7)
I don't now why it has changed on 27d34098a331e4468a02adf65108bf74cae39ed7,
In monero repository it 544e6fcc73c5ad9af48a8985c94f0f1d742ef2e0.
Please close this PR, i fix it and PR again.

**Comment by DJVova** [comment]
Miniupnp submodule fixed, i check it on windows machine - no errors, tomorrow will check on Ubuntu. You also can check this.
Do you have to close the current PR and then open a new one? Or can you immediately accept the fixes?

**Comment by one-and-only** [comment]
no no. this PR is fine. I'll check your fix soon. Thanks.

**Comment by one-and-only** [comment]
I get the following error when running `cmake`. cloning submodules worked fine:

```
-- Looking for strptime - found
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (MiniUPnPc)
  does not match the name of the calling package (Miniupnpc).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindMiniupnpc.cmake:39 (find_package_handle_standard_args)
  external/CMakeLists.txt:38 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find MiniUPnPc (missing: MINIUPNP_INCLUDE_DIR MINIUPNP_LIBRARY) 
-- Using in-tree miniupnpc
-- Looking for libunbound
CMake Error at CMakeLists.txt:116 (message):
  Could not find libunbound
Call Stack (most recent call first):
  external/CMakeLists.txt:59 (die)
```

**Comment by one-and-only** [comment]
do I need to have libunbound installed in my system?

**Comment by DJVova** [comment]
About Cmake Miniupnpc error: It's not error - only warning in new Cmake version. I didn't touch this part of code. In version 3.2.2 - same warning. It's need fix, but it not critical.

About libunbound: Yes, you only need to have libunbound installed in system, but now you don't have to compile it every time when you build SWAP.

**Comment by one-and-only** [comment]
yes, I know now. Hence why I deleted my comments. Swap builds fine in linux now. I'm testing functionality.

**Review by one-and-only — APPROVED** [review]
Code compiles in Linux and `swapd` syncs with the blockchain successfully.

**Pull request merged**
